import type { Name } from "./schema";
import { nameCategories } from "./schema";

export const namesData: InsertName[] = [
  {
    arabicName: "الرَّحْمَنُ",
    transliteration: "Ar-Rahman",
    pronunciation: "ar-RAH-maan",
    meaning: "The Most Gracious",
    description: "The Most Gracious - The One who has plenty of mercy for the believers and the blasphemers in this world and especially for the believers in the hereafter.",
    detailedExplanation: "Beloved seekers, let your heart be an open vessel, ready to receive without measure. Ar-Rahman represents boundless love, as vast as the ocean. This name teaches us that divine mercy flows continuously, touching every aspect of existence with its gentle grace. It is a reminder that in every moment, we are surrounded by unlimited compassion and care.",
    innerMeaning: "Within the depths of your heart flows a mercy as vast as the oceans. This divine quality of boundless compassion exists as a seed within every soul, waiting to blossom. When you connect with Ar-Rahman, you tap into this infinite wellspring of mercy that dissolves all boundaries and embraces all of creation without discrimination.",
    technique: "Practice loving-kindness meditation, starting with yourself and gradually expanding to include all beings. Begin each day by setting an intention to embody divine mercy in your interactions. When faced with difficulty, pause and ask: 'How would infinite compassion respond in this moment?' Let your heart soften and expand beyond its usual limits.",
    relatedNames: ["Ar-Raheem", "Al-Latif", "Al-Wadud"],
    orderNumber: 1,
    id: 1,
    category: nameCategories.MERCY,
    quranVerses: [
      {
        verse: "In the name of Allah, the Most Gracious, the Most Merciful",
        reference: "1:1",
        arabicText: "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
        explanation: "This verse, known as the Bismillah, appears at the beginning of 113 chapters of the Quran, emphasizing the all-encompassing nature of divine mercy."
      },
      {
        verse: "The Most Merciful, taught the Quran, created man, taught him eloquence.",
        reference: "55:1-4",
        arabicText: "الرَّحْمَٰنُ عَلَّمَ الْقُرْآنَ خَلَقَ الْإِنسَانَ عَلَّمَهُ الْبَيَانَ",
        explanation: "These verses directly connect Ar-Rahman with divine teaching and the creation of humanity, showing how mercy manifests through knowledge and understanding."
      }
    ]
  },
  {
    arabicName: "الرَّحِيمُ",
    transliteration: "Ar-Raheem",
    pronunciation: "ar-ra-HEEM",
    meaning: "The Most Merciful",
    description: "The Most Merciful - The One who has plenty of mercy for the believers.",
    detailedExplanation: "Ar-Raheem, the Most Merciful, speaks to the tender compassion of the Divine. This name highlights God's unwavering love and care for those who believe, offering solace and comfort in times of need.  It reminds us that mercy is not merely a concept, but a living force that sustains and protects.",
    innerMeaning: "While Ar-Rahman points to the vast ocean of divine mercy, Ar-Raheem represents the intimate rain of mercy that penetrates deeply into each receptive heart. This quality of focused, nurturing mercy exists within you as the capacity to offer profound care and healing to yourself and others. It is the gentle rain that brings life to parched soil.",
    technique: "When reciting this name, envision divine mercy as a healing light penetrating every cell of your being. Practice random acts of kindness with focused attention on the recipient's heart. Before sleep, review your day and send healing mercy to any situations or relationships that need resolution.",
    relatedNames: ["Ar-Rahman", "Al-Latif", "Al-Wadud"],
    orderNumber: 2,
    category: nameCategories.MERCY,
    quranVerses: [
      {
        verse: "And He is ever Merciful to the believers.",
        reference: "33:43",
        arabicText: "وَكَانَ بِالْمُؤْمِنِينَ رَحِيمًا",
        explanation: "This verse emphasizes the special mercy that Allah shows to the believers, highlighting the nurturing aspect of divine compassion."
      },
      {
        verse: "My mercy embraces all things.",
        reference: "7:156",
        arabicText: "وَرَحْمَتِي وَسِعَتْ كُلَّ شَيْءٍ",
        explanation: "This verse reveals the all-encompassing nature of divine mercy, showing how it extends to every aspect of creation."
      }
    ]
  },
  {
    arabicName: "الْمَلِكُ",
    transliteration: "Al-Malik",
    pronunciation: "al-MA-lik",
    meaning: "The King",
    description: "The King - The One with complete dominion, the One whose dominion is clear from imperfection.",
    detailedExplanation: "Al-Malik, the King, signifies absolute sovereignty and perfect governance.  This name reminds us that God's power is absolute, His rule just and unwavering. It inspires awe and reverence, reminding us of the majesty and authority of the Divine.",
    innerMeaning: "Within you resides a kingly power, a sense of inherent authority that is both just and benevolent. This is the strength that allows you to align with divine governance, leading with integrity and compassion.  It is not a power to control, but a capacity to serve.",
    technique: "Practice mindful leadership, whether in personal relationships or community initiatives. Cultivate a sense of inner authority by aligning your actions with your highest values.  Engage in practices that bring you into a state of grounded presence, such as yoga or tai chi.",
    relatedNames: ["Al-Maalik", "Al-Aziz", "Al-Jabbar"],
    orderNumber: 3,
    category: nameCategories.POWER
  },
  {
    arabicName: "الْقُدُّوسُ",
    transliteration: "Al-Quddus",
    pronunciation: "al-QUDD-oos",
    meaning: "The Most Sacred",
    description: "The Most Sacred - The One who is pure from any imperfection and clear from children and adversaries.",
    detailedExplanation: "Al-Quddus, the Most Sacred, speaks to the absolute purity and holiness of God.  This name transcends human understanding of purity, representing a state beyond all imperfection and blemish.  It inspires a deep sense of reverence and respect for the Divine.",
    innerMeaning: "This name reveals the inherent sanctity within your being, a divine spark of purity that is untouched by the world's imperfections.  Connecting with Al-Quddus allows you to access this inner sanctuary, a place of stillness and profound peace. It is a reminder of your inherent worthiness.",
    technique: "Practice daily purification rituals such as prayer or meditation. Engage in acts of service that express your respect for the sacredness of life.  Cultivate a daily practice of self-reflection to identify and release any impurities that cloud your inner light.",
    relatedNames: ["As-Salam", "Al-Mu'min", "Al-Muhaymin"],
    orderNumber: 4,
    category: nameCategories.HOLINESS
  },
  {
    arabicName: "السَّلاَمُ",
    transliteration: "As-Salam",
    pronunciation: "as-sa-LAAM",
    meaning: "The Source of Peace",
    description: "The Source of Peace - The One who is free from every imperfection and defect.",
    detailedExplanation: "As-Salam, the Source of Peace, embodies tranquility and serenity. This name reminds us that true peace originates from the Divine, a peace that surpasses worldly understanding. It invites us to seek inner peace and harmony, knowing that God is the ultimate source of calm and composure.",
    innerMeaning: "You are inherently connected to the boundless peace of the divine. As-Salam is a reminder that this peace is your birthright and can be accessed anytime, regardless of external circumstances. The path to this peace begins with recognizing the source of your own inner turbulence.",
    technique: "Practice deep, conscious breathing. Engage in activities that bring you a sense of calm, such as spending time in nature or listening to soothing music.  When facing conflict, pause, take a deep breath and ground yourself in the awareness of your inner peace.",
    relatedNames: ["Al-Mu'min", "Al-Muhaymin", "Al-Quddus"],
    orderNumber: 5,
    category: nameCategories.PEACE
  },
  {
    arabicName: "الْمُؤْمِنُ",
    transliteration: "Al-Mu'min",
    pronunciation: "al-MU-min",
    meaning: "The Guardian of Faith",
    description: "The Guardian of Faith - The One who witnessed for Himself that no one is God but Him. And He witnessed for His believers that they are truthful in their belief that no one is God but Him.",
    detailedExplanation: "Al-Mu'min, the Guardian of Faith, is a testament to God's unwavering commitment to those who believe.  This name offers strength and reassurance, emphasizing the Divine's steadfast support and protection for those who trust in Him. It is a beacon of hope in the face of adversity.",
    innerMeaning: "This name reveals the unshakeable foundation of faith that exists within you. Al-Mu'min is the unwavering trust in the divine, the knowing that you are always supported and guided, even in the face of doubt or fear. It is the strength that sustains you through life's challenges.",
    technique: "Practice affirmations that reinforce your faith and trust in the divine. Engage in acts of service that reflect your commitment to your beliefs.  When facing doubt, recall moments of unwavering faith and let that strength guide you.",
    relatedNames: ["Al-Muhaymin", "As-Salam", "Al-Quddus"],
    orderNumber: 6,
    category: nameCategories.FAITH
  },
  {
    arabicName: "الْمُهَيْمِنُ",
    transliteration: "Al-Muhaymin",
    pronunciation: "al-mu-HAY-min",
    meaning: "The Protector",
    description: "The Protector - The One who witnesses the saying and deeds of His creatures.",
    detailedExplanation: "Al-Muhaymin, the Protector, signifies God's constant watchfulness and care. This name assures us that we are never alone, always under the watchful eye of the Divine. It offers comfort and security, reminding us that God's protection encompasses all aspects of our lives.",
    innerMeaning: "Al-Muhaymin embodies the divine protection that surrounds and sustains you at all times. This is not a protection from challenges, but a presence that allows you to navigate life's difficulties with strength and resilience.  It is the unwavering support that allows you to grow and evolve.",
    technique: "Practice mindfulness to cultivate an awareness of your surroundings and the forces at play in your life. Visualize yourself surrounded by a protective light, allowing you to feel safe and secure.  When facing danger, call upon the divine protector within you.",
    relatedNames: ["Al-Mu'min", "Al-Hafiz", "Al-Wakil"],
    orderNumber: 7,
    category: nameCategories.PROTECTION
  },
  {
    arabicName: "الْعَزِيزُ",
    transliteration: "Al-Aziz",
    pronunciation: "al-a-ZEEZ",
    meaning: "The Almighty",
    description: "The Almighty - The Strong, The Defeater who is not defeated.",
    detailedExplanation: "Al-Aziz, the Almighty, represents the boundless power and might of God. This name inspires reverence and respect, highlighting God's absolute dominion over all creation. It is a reminder of the ultimate authority and strength of the Divine.",
    innerMeaning: "This name connects you to the boundless strength and resilience that exists within you. It is a reminder that you are capable of overcoming any obstacle, as long as you align yourself with the divine source of power.  It is the unwavering strength that empowers you to face any challenge.",
    technique: "Practice strength-building activities that nourish both your body and spirit.  Engage in activities that push your boundaries and expand your sense of capacity.  When faced with a challenge, call upon the inner strength that dwells within you.",
    relatedNames: ["Al-Qawi", "Al-Malik", "Al-Jabbar"],
    orderNumber: 8,
    category: nameCategories.POWER
  },
  {
    arabicName: "الْجَبَّارُ",
    transliteration: "Al-Jabbar",
    pronunciation: "al-jabb-AAR",
    meaning: "The Compeller",
    description: "The Compeller - The One that nothing happens in His dominion except what He willed.",
    detailedExplanation: "Al-Jabbar, the Compeller, emphasizes God's absolute will and control over all events.  This name reminds us that everything happens according to God's plan, and that even seemingly random events are part of a larger, divinely orchestrated design.  It fosters trust and acceptance in the face of uncertainty.",
    innerMeaning: "This name connects you to the power of divine will, the understanding that even in chaos, there is a larger plan at work.  It is the capacity to surrender to the flow of life, trusting that even in difficult times, there is a divine purpose. It is a source of strength and resilience.",
    technique: "Practice surrendering to the unknown.  When faced with uncertainty, trust that there is a larger plan in motion.  Engage in practices that help you to let go of control, such as meditation or yoga.",
    relatedNames: ["Al-Aziz", "Al-Malik", "Al-Mutakabbir"],
    orderNumber: 9,
    category: nameCategories.POWER
  },
  {
    arabicName: "الْمُتَكَبِّرُ",
    transliteration: "Al-Mutakabbir",
    pronunciation: "al-mu-ta-KAB-bir",
    meaning: "The Greatest",
    description: "The Greatest - The One who is clear from the attributes of the creatures and from resembling them.",
    detailedExplanation: "Al-Mutakabbir, the Greatest, signifies God's transcendence and majesty. This name surpasses all human comprehension of greatness, representing a state beyond all comparison. It evokes a profound sense of awe and wonder at the Divine's immeasurable glory.",
    innerMeaning: "This name reveals the boundless potential for greatness that exists within you.  It is the capacity to rise above limitations and embrace your full potential.  It is a reminder that you are a child of the Divine, capable of achieving anything you set your mind to.",
    technique: "Practice setting ambitious goals and working towards them with unwavering determination.  Cultivate a sense of self-respect and self-worth.  When faced with setbacks, remember that your greatness is intrinsic and cannot be diminished by external forces.",
    relatedNames: ["Al-Kabir", "Al-Azim", "Al-Jalil"],
    orderNumber: 10,
    category: nameCategories.GREATNESS
  },
  {
    arabicName: "الْخَالِقُ",
    transliteration: "Al-Khaliq",
    pronunciation: "al-KHA-liq",
    meaning: "The Creator",
    description: "The Creator - The One who brings everything from non-existence to existence.",
    detailedExplanation: "Al-Khaliq, the Creator, speaks to the boundless power of God to bring forth existence from nothingness. This name reminds us of the miracle of creation, the intricate beauty and complexity of the universe, and the divine hand that shaped it all. It instills a deep appreciation for the wonder of creation.",
    innerMeaning: "This name connects you to the creative power that resides within you, the capacity to bring forth new ideas, projects, and possibilities.  It is the spark of innovation that allows you to shape your reality and create a life that is both meaningful and fulfilling.",
    technique: "Engage in creative activities that allow you to express your inner vision.  Practice visualizing your goals and creating a clear path towards their manifestation.  When faced with creative blocks, remember that your capacity for creation is boundless.",
    relatedNames: ["Al-Bari", "Al-Musawwir"],
    orderNumber: 11,
    id: 11,
    category: nameCategories.CREATION
  },
  {
    arabicName: "الْبَارِئُ",
    transliteration: "Al-Bari",
    pronunciation: "al-BAA-ri",
    meaning: "The Maker of Order",
    description: "The Maker of Order - The One who creates things with subtle knowledge.",
    detailedExplanation: "Al-Bari, the Maker of Order, highlights God's meticulous craftsmanship in creating the universe.  This name emphasizes the intricate balance and harmony found in creation, a testament to God's wisdom and precision. It inspires a deeper understanding of the order and purpose within the cosmos.",
    innerMeaning: "This name connects you to the capacity to bring order and structure into your life.  It is the ability to organize your thoughts, actions, and environment in a way that supports your well-being and allows you to achieve your goals. It's about creating harmony and balance.",
    technique: "Practice organizing and decluttering your physical space. Create routines and systems that support your productivity and well-being. When faced with chaos, remember that your capacity to bring order is a gift from the divine.",
    relatedNames: ["Al-Khaliq", "Al-Musawwir"],
    orderNumber: 12,
    id: 12,
    category: nameCategories.CREATION
  },
  {
    arabicName: "الْمُصَوِّرُ",
    transliteration: "Al-Musawwir",
    pronunciation: "al-mu-SAW-wir",
    meaning: "The Shaper of Beauty",
    description: "The Shaper of Beauty - The One who shapes creatures and perfects their forms.",
    detailedExplanation: "Al-Musawwir, the Shaper of Beauty, speaks to the aesthetic perfection and artistry of God's creation.  This name reminds us of the beauty and wonder that surrounds us, a testament to the Divine's creative power and artistic flair. It inspires a deeper appreciation for the beauty and harmony of the world.",
    innerMeaning: "This name connects you to the ability to appreciate and create beauty in all aspects of your life. It's about recognizing the inherent beauty in yourself and the world around you and using that as inspiration to create something beautiful.",
    technique: "Practice cultivating an appreciation for beauty in your daily life. Engage in creative activities that allow you to express your artistic talents.  When faced with ugliness, remember that your capacity to see and create beauty is a gift from the divine.",
    relatedNames: ["Al-Khaliq", "Al-Bari"],
    orderNumber: 13,
    id: 13,
    category: nameCategories.CREATION
  },
  {
    arabicName: "الْغَفَّارُ",
    transliteration: "Al-Ghaffar",
    pronunciation: "al-ghaf-FAAR",
    meaning: "The Forgiver",
    description: "The Forgiver - The One who forgives the sins of His servants time and time again.",
    detailedExplanation: "Al-Ghaffar, the Forgiver, emphasizes God's boundless capacity for forgiveness. This name offers hope and redemption, reminding us that God's mercy extends even to those who have strayed. It encourages repentance and the pursuit of forgiveness.",
    innerMeaning: "This name connects you to the boundless capacity for forgiveness that resides within you. It's about letting go of resentment and embracing compassion, both towards yourself and others. It’s a journey of self-acceptance and growth.",
    technique: "Practice self-forgiveness.  Let go of past mistakes and embrace the opportunity for growth.  When faced with the transgressions of others, extend forgiveness and compassion. Remember that true forgiveness sets you free.",
    relatedNames: ["At-Tawwab", "Al-'Afuw"],
    orderNumber: 14,
    id: 14,
    category: nameCategories.FORGIVENESS
  },
  {
    arabicName: "الْقَهَّارُ",
    transliteration: "Al-Qahhar",
    pronunciation: "al-qah-HAAR",
    meaning: "The Subduer",
    description: "The Subduer - The One who has the perfect Power and is not unable over anything.",
    detailedExplanation: "Al-Qahhar, the Subduer, highlights God's absolute power and authority. This name reminds us that God is in control, capable of overcoming any obstacle or adversary.  It inspires confidence and trust in the face of challenges.",
    innerMeaning: "This name connects you to the inner strength and resilience needed to overcome challenges and obstacles. It’s about harnessing your inner power to conquer negativity and transform adversity into opportunity. It is about mastery, not domination.",
    technique: "Practice self-discipline and self-control.  Set clear boundaries and learn to say no when necessary.  When faced with challenges, remember that your capacity for overcoming obstacles is a reflection of divine power.",
    relatedNames: ["Al-Jabbar", "Al-Aziz"],
    orderNumber: 15,
    id: 15,
    category: nameCategories.POWER
  },
  {
    arabicName: "الْوَهَّابُ",
    transliteration: "Al-Wahhab",
    pronunciation: "al-wah-HAAB",
    meaning: "The Giver of All",
    description: "The Giver of All - The One who gives freely without expecting any return.",
    detailedExplanation: "Al-Wahhab, the Giver of All, emphasizes God's generosity and abundance. This name reminds us that all blessings and gifts originate from the Divine, freely given without expectation of recompense. It inspires gratitude and appreciation for the gifts we receive.",
    innerMeaning: "This name connects you to the boundless generosity and abundance that exists within you. It's about recognizing your capacity to give freely and unconditionally, both materially and spiritually. It is the act of giving that enriches you.",
    technique: "Practice giving freely and without expectation of return.  Share your time, talents, and resources with those in need.  When faced with scarcity, remember that your capacity for generosity is a reflection of divine abundance.",
    relatedNames: ["Al-Karim", "Ar-Razzaq"],
    orderNumber: 16,
    id: 16,
    category: nameCategories.GIVING
  },
  {
    arabicName: "الرَّزَّاقُ",
    transliteration: "Ar-Razzaq",
    pronunciation: "ar-raz-ZAAQ",
    meaning: "The Sustainer",
    description: "The Sustainer - The One who creates all means of nourishment and sustenance.",
    detailedExplanation: "Ar-Razzaq, the Sustainer, highlights God's provision for all of creation. This name reminds us that God provides for all our needs, both material and spiritual. It inspires trust and reliance on the Divine's provision.",
    innerMeaning: "This name connects you to the divine abundance that sustains you at all times. It's about recognizing the flow of provision in your life and trusting in the divine support that meets your needs, both material and spiritual. It is about abundance, not scarcity.",
    technique: "Practice gratitude for the abundance in your life.  Trust in the divine provision that meets your needs. When faced with lack, remember that your capacity for receiving is limitless.",
    relatedNames: ["Al-Wahhab", "Al-Karim"],
    orderNumber: 17,
    id: 17,
    category: nameCategories.SUSTENANCE
  },
  {
    arabicName: "الْفَتَّاحُ",
    transliteration: "Al-Fattah",
    pronunciation: "al-fat-TAAH",
    meaning: "The Opener",
    description: "The Opener - The One who opens the closed, whether it be gates of mercy or sustenance.",
    detailedExplanation: "Al-Fattah, the Opener, signifies God's power to remove obstacles and open doors to opportunities. This name inspires hope and faith, reminding us that God can overcome any challenge and open paths to success and fulfillment. It encourages perseverance and trust in the Divine's guidance.",
    innerMeaning: "This name connects you to the divine power to remove obstacles and create opportunities. It is the ability to open doors to new possibilities and overcome challenges with grace and resilience. It is about expanding your horizons.",
    technique: "Practice visualizing your goals and removing any obstacles that stand in your way.  Maintain a positive and hopeful attitude. When faced with challenges, remember that the divine power can open any door.",
    relatedNames: ["An-Nafi", "Al-Hadi"],
    orderNumber: 18,
    id: 18,
    category: nameCategories.OPENING
  },
  {
    arabicName: "اَلْعَلِيْمُ",
    transliteration: "Al-Alim",
    pronunciation: "al-a-LEEM",
    meaning: "The All-Knowing",
    description: "The All-Knowing - The One who knows everything in the past, present and future.",
    detailedExplanation: "Al-Alim, the All-Knowing, represents God's infinite wisdom and understanding. This name reminds us that God is aware of everything, past, present, and future. It inspires humility and respect for the Divine's omniscience.",
    innerMeaning: "This name connects you to the wisdom and insight that comes from aligning with the divine. It's about trusting your intuition and inner knowing, recognizing that you have access to a deeper understanding of yourself and the world around you.",
    technique: "Practice cultivating intuition and inner wisdom.  Pay attention to your inner voice and trust your gut feelings.  When faced with difficult decisions, remember that you have access to a higher level of understanding.",
    relatedNames: ["Al-Khabir", "Al-Hakim"],
    orderNumber: 19,
    id: 19,
    category: nameCategories.KNOWLEDGE
  },
  {
    arabicName: "الْقَابِضُ",
    transliteration: "Al-Qabid",
    pronunciation: "al-QAA-bid",
    meaning: "The Constrictor",
    description: "The Constrictor - The One who constricts and withholds.",
    detailedExplanation: "Al-Qabid, the Constrictor, highlights God's power to withhold and control. This name reminds us that God has the power to limit and restrict, often to test our faith and patience. It encourages humility and acceptance of God's will.",
    innerMeaning: "This name helps you to recognize the ebb and flow of life, the times of abundance and the times of scarcity.  It is about accepting the limitations that are placed upon you, knowing that these limitations are often necessary for growth and transformation.",
    technique: "Practice acceptance of limitations.  When faced with scarcity, remember that it is often a necessary step towards greater abundance.  Cultivate patience and trust in divine timing.",
    relatedNames: ["Al-Basit", "Al-Muqsit"],
    orderNumber: 20,
    id: 20,
    category: nameCategories.POWER
  },
  {
    arabicName: "الْبَاسِطُ",
    transliteration: "Al-Basit",
    pronunciation: "al-BAA-sit",
    meaning: "The Expander",
    description: "The Expander - The One who has the power to expand, enlarge, and extend.",
    detailedExplanation: "Al-Basit, the Expander, emphasizes God's power to provide and bestow abundance. This name offers hope and reassurance, reminding us that God can expand our horizons and increase our blessings. It inspires gratitude and trust in the Divine's generosity.",
    innerMeaning: "This name connects you to the boundless potential for expansion and growth that exists within you. It's about embracing new opportunities and pushing your boundaries, knowing that your capacity for growth is limitless.",
    technique: "Practice setting expansive goals and working towards them with unwavering determination.  Embrace new opportunities and step outside your comfort zone. When faced with limitations, remember that your capacity for expansion is limitless.",
    relatedNames: ["Al-Qabid", "Al-Muqsit"],
    orderNumber: 21,
    category: nameCategories.POWER
  },
  {
    arabicName: "الْخَافِضُ",
    transliteration: "Al-Khafid",
    pronunciation: "al-KHAA-fid",
    meaning: "The Abaser",
    description: "The Abaser - The One who lowers whoever He willed by His Destruction and raises whoever He willed by His Endowment.",
    detailedExplanation: "Al-Khafid, the Abaser, highlights God's power to humble and lower those who defy Him.  This name reminds us that arrogance and pride are ultimately futile, and that true strength lies in humility and submission to God's will.",
    innerMeaning: "This name helps you to recognize the importance of humility and surrender.  It's about letting go of ego and pride, recognizing that true strength comes from aligning with the divine will.  It is a reminder that growth often comes from surrendering to the process.",
    technique: "Practice humility and self-reflection.  Let go of ego and pride.  When faced with challenges, remember that humility is a source of strength.",
    relatedNames: ["Ar-Rafi", "Al-Mu'izz", "Al-Muzil"],
    orderNumber: 22,
    category: nameCategories.POWER
  },
  {
    arabicName: "الرَّافِعُ",
    transliteration: "Ar-Rafi",
    pronunciation: "ar-RAA-fi",
    meaning: "The Exalter",
    description: "The Exalter - The One who raises the believers in rank through their obedience to Him.",
    detailedExplanation: "Ar-Rafi, the Exalter, emphasizes God's power to elevate and honor those who serve Him. This name offers encouragement and hope, reminding us that through faith and obedience, we can achieve spiritual growth and attain a higher station in the eyes of God.",
    innerMeaning: "This name connects you to the divine potential for growth and elevation.  It's about recognizing your capacity to rise above challenges and reach your full potential. It is about striving for excellence and making a positive impact on the world.",
    technique: "Practice setting high standards and working towards them with unwavering determination.  Cultivate a sense of self-belief and self-confidence.  When faced with setbacks, remember that your capacity for growth is limitless.",
    relatedNames: ["Al-Khafid", "Al-Mu'izz", "Al-Muzil"],
    orderNumber: 23,
    category: nameCategories.POWER
  },
  {
    arabicName: "الْمُعِزُّ",
    transliteration: "Al-Mu'izz",
    pronunciation: "al-mu-IZZ",
    meaning: "The Bestower of Honors",
    description: "The Bestower of Honors - The One who gives esteem to whoever He willed, hence there is no one to degrade Him.",
    detailedExplanation: "Al-Mu'izz, the Bestower of Honors, signifies God's power to grant dignity and respect.  This name reminds us that true honor comes from God, and that those who seek His favor will be elevated and esteemed. It inspires humility and a striving for spiritual excellence.",
    innerMeaning: "This name connects you to the divine capacity to bestow honor and dignity upon yourself and others. It's about recognizing your inherent worth and treating yourself and others with respect and compassion. It's about living with integrity and purpose.",
    technique: "Practice treating yourself and others with respect and dignity.  Live in alignment with your values.  When faced with disrespect, remember that your inherent worth is independent of external validation.",
    relatedNames: ["Al-Muzil", "Ar-Rafi", "Al-Khafid"],
    orderNumber: 24,
    category: nameCategories.POWER
  },
  {
    arabicName: "المُذِلُّ",
    transliteration: "Al-Muzil",
    pronunciation: "al-mu-ZIL",
    meaning: "The Humiliator",
    description: "The Humiliator - The One who degrades whoever He willed, hence there is no one to give them esteem.",
    detailedExplanation: "Al-Muzil, the Humiliator, highlights God's power to bring down those who are arrogant and defy Him. This name serves as a reminder of the consequences of disobedience and the importance of humility. It encourages a sense of humility and submission to God's will.",
    innerMeaning: "This name is a reminder of the consequences of arrogance and pride. It's about recognizing the importance of humility and surrender, understanding that true strength comes from aligning with the divine will. It's about letting go of ego and embracing vulnerability.",
    technique: "Practice self-reflection and identify any areas where arrogance or pride might be holding you back.  Cultivate humility and surrender to the divine will. When faced with arrogance, remember that true strength lies in humility.",
    relatedNames: ["Al-Mu'izz", "Al-Khafid", "Ar-Rafi"],
    orderNumber: 25,
    category: nameCategories.POWER
  },
  {
    arabicName: "السَّمِيعُ",
    transliteration: "As-Sami",
    pronunciation: "as-sa-MI",
    meaning: "The All-Hearing",
    description: "The All-Hearing - The One who hears all things that are heard by His eternal hearing without an ear, instrument or organ.",
    detailedExplanation: "As-Sami', the All-Hearing, represents God's awareness of all sounds and whispers.  This name reminds us that our prayers, hopes, and concerns are always heard by God, even the unspoken ones.  It inspires trust and faith in the Divine's attentiveness.",
    innerMeaning: "This name connects you to the divine capacity to listen deeply and compassionately.  It's about recognizing the importance of active listening and creating space for others to share their thoughts and feelings. It's about creating a safe space for vulnerability.",
    technique: "Practice active listening. Pay close attention to what others are saying, both verbally and nonverbally. Create space for others to share their thoughts and feelings without judgment. When faced with conflict, remember that listening is a powerful tool for resolution.",
    relatedNames: ["Al-Basir", "Al-Khabir"],
    orderNumber: 26,
    category: nameCategories.ATTRIBUTES,
    quranVerses: [
      {
        verse: "Indeed, Allah is ever Hearing and Seeing.",
        reference: "4:58", 
        arabicText: "إِنَّ اللَّهَ كَانَ سَمِيعًا بَصِيرًا",
        explanation: "This verse emphasizes Allah's perfect ability to hear all things, highlighting the comprehensive nature of divine hearing."
      },
      {
        verse: "Our Lord, indeed You are the Hearing, the Knowing.",
        reference: "2:127",
        arabicText: "رَبَّنَا تَقَبَّلْ مِنَّا ۖ إِنَّكَ أَنتَ السَّمِيعُ الْعَلِيمُ",
        explanation: "This prayer of Ibrahim emphasizes how Allah hears all supplications and knows the intentions behind them."
      }
    ]
  },
  {
    arabicName: "المتعالي",
    transliteration: "Al-Muta'ali",
    pronunciation: "Al-Mu-ta-'aa-lee",meaning: "The Exalted",
    description: '"Al-Muta\'ali (Al-Mu-ta-\'aa-lee)" translates as "The Exalted," "The Supreme," or "The Transcendent." Derived from the Arabic root Ta\'ala (تعالى), meaning to be exalted, elevated, or transcendent, this attribute emphasizes Allah\'s absolute exaltation above creation, transcending all limits, boundaries, and comparisons.',
    detailedExplanation: 'Mystics interpret "Al-Muta\'ali (Al-Mu-ta-\'aa-lee)" as signifying Allah\'s supreme transcendence, guiding believers toward humility and reverence. Reflecting upon this attribute inspires awe, respect, and recognition of human limitations, acknowledging that ultimate greatness and perfection belong exclusively to Allah.',
    innerMeaning: "This name connects you to the divine capacity for transcendence and elevation. It’s about rising above limitations and embracing your full potential. It’s about living a life of purpose and meaning, guided by your highest aspirations.",
    technique: "Practice mindfulness and meditation to connect with your higher self. Set ambitious goals and work towards them with unwavering determination. When faced with limitations, remember that your capacity for transcendence is limitless.",
    relatedNames: ["Al-Ali", "Al-Kabir"],
    orderNumber: 78,
    category: nameCategories.GREATNESS,
    quranVerses: [
      {
        verse: "He is the Grand, the Exalted.",
        reference: "13:9",
        arabicText: "الْكَبِيرُ الْمُتَعَالِ",
        explanation: "This verse directly mentions the name Al-Muta'ali, emphasizing Allah's supreme elevation above all creation."
      },
      {
        verse: "[He is] Knower of the unseen and the witnessed, the Grand, the Exalted.",
        reference: "13:9",
        arabicText: "عَالِمُ الْغَيْبِ وَالشَّهَادَةِ الْكَبِيرُ الْمُتَعَالِ",
        explanation: "This verse connects Allah's exalted nature with His comprehensive knowledge of all things, visible and invisible."
      }
    ]
  },
  {
    arabicName: "الْبَرُّ",
    transliteration: "Al-Barr",
    pronunciation: "al-BARR",
    meaning: "The Source of All Good",
    description: "The Source of All Good - The One who is kind to His creatures, who covered them with His sustenance and specified whoever He willed among them by His support, protection, and special mercy.",
    detailedExplanation: "Al-Barr, the Source of All Good, emphasizes God's inherent goodness and benevolence. This name reminds us that God is the source of all blessings and kindness, showering His creation with His mercy and compassion. It inspires gratitude and a deeper appreciation for God's goodness.",
    innerMeaning: "This name connects you to the divine source of goodness and benevolence. It’s about recognizing your own capacity for kindness and compassion, and extending that to others. It’s about living a life of service and generosity.",
    technique: "Practice acts of kindness and compassion. Share your time, talents, and resources with others. When faced with negativity, remember that your capacity for goodness is limitless.",
    relatedNames: ["Ar-Rahman", "Ar-Rahim", "Al-Karim"],
    orderNumber: 79,
    id: 79,
    category: nameCategories.GOODNESS,
    quranVerses: [
      {
        verse: "Indeed, He is the Most Beneficent, the Most Merciful.",
        reference: "52:28",
        arabicText: "إِنَّهُ هُوَ الْبَرُّ الرَّحِيمُ",
        explanation: "This verse directly mentions Al-Barr, highlighting Allah's perfect benevolence and mercy towards His creation."
      },
      {
        verse: "And We will increase them from Our bounty, and indeed, Allah is Forgiving and Appreciative.",
        reference: "35:30",
        arabicText: "وَيَزِيدَهُم مِّن فَضْلِهِ ۚ إِنَّهُ غَفُورٌ شَكُورٌ",
        explanation: "This verse demonstrates Allah's boundless generosity and kindness towards those who do good."
      }
    ]
  },
  {
    arabicName: "التَّوَّابُ",
    transliteration: "At-Tawwab",
    pronunciation: "at-taw-WAAB",
    meaning: "The Ever-Accepting of Repentance",
    description: "The Ever-Accepting of Repentance - The One who grants repentance to whoever He willed among His creatures and accepts his repentance.",
    detailedExplanation: "At-Tawwab, the Ever-Accepting of Repentance, highlights God's willingness to forgive and accept those who sincerely repent. This name offers hope and redemption, reminding us that God is always ready to forgive our mistakes and guide us back to the right path. It encourages repentance and a renewed commitment to righteousness.",
    innerMeaning: "This name connects you to the divine capacity for forgiveness and renewal. It’s about recognizing the importance of self-forgiveness and embracing the opportunity for growth and transformation. It’s about hope and redemption.",
    technique: "Practice self-forgiveness and repentance.  Let go of past mistakes and embrace the opportunity for growth.  When faced with challenges, remember that your capacity for renewal is limitless.",
    relatedNames: ["Al-Ghaffar", "Al-Afuw"],
    orderNumber: 80,
    category: nameCategories.REPENTANCE
  },
  {
    arabicName: "الْمُنْتَقِمُ",
    transliteration: "Al-Muntaqim",
    pronunciation: "al-mun-ta-QIM",
    meaning: "The Avenger",
    description: "The Avenger - The One who victoriously prevails over His enemies and punishes them for their sins. It may mean the One who destroys them.",
    detailedExplanation: "Al-Muntaqim, the Avenger, emphasizes God's justice and retribution against those who defy Him. This name reminds us that God will ultimately hold everyone accountable for their actions, and that justice will prevail. It encourages righteous conduct and a fear of God's punishment.",
    innerMeaning: "This name connects you to the divine capacity for justice and accountability.  It’s about recognizing the importance of upholding righteousness and taking responsibility for your actions. It’s about integrity and justice.",
    technique: "Practice living in alignment with your values and upholding justice.  When faced with injustice, remember that your capacity for justice is a gift from the divine.",
    relatedNames: ["Al-Aziz", "Al-Qahhar"],
    orderNumber: 81,
    category: nameCategories.JUDGEMENT
  },
  {
    arabicName: "العَفُوُّ",
    transliteration: "Al-'Afuw",
    pronunciation: "al-a-FOO",
    meaning: "The Pardoner",
    description: "The Pardoner - The One who forgives a lot and erases the traces of sins.",
    detailedExplanation: "Al-'Afuw, the Pardoner, signifies God's capacity to forgive and erase sins completely. This name offers comfort and hope, reminding us that God's forgiveness is total and complete, erasing the traces of past transgressions. It encourages repentance and a renewed commitment to righteousness.",
    innerMeaning: "Forgiveness is the key to liberating your inner self from the chains of resentment and regret. \"Al-'Afuww\" invites you to forgive not only others but also yourself, unlocking the freedom that comes from unconditional acceptance.",
    technique: "Practice self-forgiveness and compassion.  Let go of past mistakes and embrace the opportunity for growth. When faced with the transgressions of others, extend forgiveness and compassion. Remember that true forgiveness sets you free.",
    relatedNames: ["Al-Ghaffar", "At-Tawwab"],
    orderNumber: 82,
    category: nameCategories.FORGIVENESS
  },
  {
    arabicName: "الرَّؤُوفُ",
    transliteration: "Ar-Ra'uf",
    pronunciation: "ar-ra-OO",
    meaning: "The Most Kind",
    description: "The Most Kind - The One who is very compassionate with His creatures.",
    detailedExplanation: "Ar-Ra'uf, the Most Kind, emphasizes God's compassionate and merciful nature.  This name reminds us that God is always kind and compassionate towards His creation, showing mercy and understanding. It inspires a life of kindness and compassion towards others.",
    innerMeaning: "A tender compassion resides within you—a nurturing, empathetic energy that heals and comforts. \"Ar-Ra'uf\" calls you to embrace that gentle care, ensuring that every part of your being feels loved and supported.",
    technique: "Practice extending kindness and compassion to others.  Share your time, talents, and resources with those in need. When faced with negativity, remember that your capacity for kindness is limitless.",
    relatedNames: ["Ar-Rahman", "Ar-Rahim"],
    orderNumber: 83,
    category: nameCategories.MERCY
  },
  {
    arabicName: "مَالِكُ الْمُلْكِ",
    transliteration: "Malik-al-Mulk",
    pronunciation: "maa-lik-al-MULK",
    meaning: "The Owner of All",
    description: "The Owner of All - The One who controls the dominion and gives dominion to whoever He willed.",
    detailedExplanation: "Malik al-Mulk, the Owner of All, emphasizes God's absolute sovereignty and dominion over all creation. This name reminds us that God is the ultimate authority, controlling all things and bestowing dominion as He sees fit. It inspires humility and submission to God's will.",
    innerMeaning: "This name connects you to the divine principle of sovereignty and dominion. It’s about recognizing the importance of living in alignment with the divine will and surrendering to the process. It’s about trust and acceptance.",
    technique: "Practice surrendering to the divine will.  Trust in the process. When faced with challenges, remember that your capacity for acceptance is limitless.",
    relatedNames: ["Al-Malik", "Al-Wali"],
    orderNumber: 84,
    category: nameCategories.POWER
  },
  {
    arabicName: "ذُوالْجَلَالِ وَالْإِكْرَامِ",
    transliteration: "Dhul-Jalali-wal-Ikram",
    pronunciation: "dhul-ja-LAA-li-wal-ik-RAAM",
    meaning: "The Lord of Majesty and Bounty",
    description: "The Lord of Majesty and Bounty - The One who has the perfect Power and Authority, and deserves to be Glorified.",
    detailedExplanation: "Dhul-Jalali wal-Ikram, the Lord of Majesty and Bounty, highlights God's supreme majesty and generosity. This name reminds us of the Divine's infinite power and boundless kindness, inspiring awe and gratitude. It encourages a life of worship and service.",
    innerMeaning: "This name connects you to the divine majesty and generosity that surrounds and sustains you.  It’s about recognizing the importance of living with grace and dignity, and extending kindness and compassion to others. It’s about gratitude and appreciation.",
    technique: "Practice gratitude and appreciation.  Live with grace and dignity. When faced with challenges, remember that your capacity for majesty is limitless.",
    relatedNames: ["Al-Majid", "Al-Karim"],
    orderNumber: 85,
    category: nameCategories.GREATNESS
  },
  {
    arabicName: "الْمُقْسِطُ",
    transliteration: "Al-Muqsit",
    pronunciation: "al-muq-SEET",
    meaning: "The Equitable One",
    description: "The Equitable One - The One who is Just in His judgment.",
    detailedExplanation: "Al-Muqsit, the Equitable One, emphasizes God's perfect justice and fairness. This name reminds us that God's judgments are always just and impartial, ensuring that everyone receives what they deserve.  It encourages righteous conduct and a commitment to justice.",
    innerMeaning: "Balance is the heartbeat of your inner world. \"Al-Muqsit\" reminds you to nurture fairness and equilibrium in all aspects of your life, ensuring that your inner scales remain aligned with the natural order of the universe.",
    technique: "Practice fairness and impartiality in your interactions.  Treat everyone with respect and dignity.  When faced with injustice, remember that your capacity for justice is a reflection of the divine will.",
    orderNumber: 86,
    category: nameCategories.JUDGEMENT
  },
  {
    arabicName: "الْجَامِعُ",
    transliteration: "Al-Jami",
    pronunciation: "al-jaa-MI",
    meaning: "The Gatherer",
    description: "The Gatherer - The One who gathers the creatures on a day that there is no doubt about, that is the Day of Judgment.",
    detailedExplanation: "Al-Jami', the Gatherer, signifies God's power to bring together all of creation on the Day of Judgment. This name reminds us of the ultimate accountability for our actions and the importance of living a life of faith and righteousness.",
    innerMeaning: "This name connects you to the divine principle of unity and wholeness.  It’s about recognizing the interconnectedness of all things and embracing a sense of belonging and community.  It’s about unity and connection.",
    technique: "Practice cultivating a sense of community and belonging.  Connect with others and share your experiences.  When faced with challenges, remember that your capacity for connection is limitless.",
    relatedNames: ["Al-Hasib", "Al-Muhsi"],
    orderNumber: 87,
    category: nameCategories.JUDGEMENT
  },
  {
    arabicName: "الْغَنِيُّ",
    transliteration: "Al-Ghaniyy",
    pronunciation: "al-gha-NEE",
    meaning: "The Self-Sufficient",
    description: "The Self-Sufficient - The One who does not need the creation.",
    detailedExplanation: "Al-Ghaniyy, the Self-Sufficient, emphasizes God's independence and lack of need for anything.  This name reminds us that God is complete in Himself, needing nothing from creation.  It inspires awe and wonder at the Divine's self-sufficiency.",
    innerMeaning: "This name connects you to the divine principle of self-sufficiency and independence. It’s about recognizing your own inner strength and resilience, and trusting in your ability to meet your own needs. It’s about self-reliance and inner peace.",
    technique: "Practice self-reliance and inner peace. Trust in your own abilities. When faced with challenges, remember that your capacity for self-sufficiency is limitless.",
    relatedNames: ["As-Samad", "Al-Wajid"],
    orderNumber: 88,
    category: nameCategories.ATTRIBUTES
  },
  {
    arabicName: "الْمُغْنِي",
    transliteration: "Al-Mughni",
    pronunciation: "al-MUGH-ni",
    meaning: "The Enricher",
    description: "The Enricher - The One who satisfies the necessities of the creatures.",
    detailedExplanation: "Al-Mughni, the Enricher, emphasizes God's ability to provide and enrich His creation. This name reminds us that God is the source of all abundance and prosperity, providing for our needs both materially and spiritually. It inspires gratitude and reliance on God's provision.",
    innerMeaning: "This name connects you to the divine energy that sustains and nourishes you. It’s about recognizing the flow of abundance in your life and trusting in the divine support that meets your needs.  It’s about receiving and appreciating.",
    technique: "Practice gratitude for the abundance in your life. Trust in the divine provision that meets your needs. When faced with lack, remember that your capacity for receiving is limitless.",
    relatedNames: ["Al-Ghaniyy", "Ar-Razzaq"],
    orderNumber: 89,
    category: nameCategories.SUSTENANCE
  },
  {
    arabicName: "اَلْمَانِعُ",
    transliteration: "Al-Mani",
    pronunciation: "al-MAA-ni",
    meaning: "The Preventer",
    description: "The Preventer - The One who prevents harmful things from reaching His creatures.",
    detailedExplanation: "Al-Mani', the Preventer, highlights God's power to protect His creation from harm. This name reminds us that God is our protector, shielding us from danger and guiding us towards safety. It inspires trust and reliance on God's protection.",
    innerMeaning: "This name connects you to the divine capacity for protection and preservation. It’s about recognizing the importance of safeguarding your well-being and nurturing your inner strength. It’s about self-care and resilience.",
    technique: "Practice self-care and prioritize your well-being. Set boundaries to protect yourself from harm. When faced with challenges, remember that your capacity for self-preservation is a gift from the divine.",
    relatedNames: ["Al-Hafiz", "Al-Wali"],
    orderNumber: 90,
    category: nameCategories.PROTECTION
  },
  {
    arabicName: "الضَّارُّ",
    transliteration: "Ad-Darr",
    pronunciation: "ad-DAARR",
    meaning: "The Creator of Harm",
    description: "The Creator of Harm - The One who makes harm reach to whoever He willed and benefits to whoever He willed.",
    detailedExplanation: "Ad-Darr, the Creator of Harm, signifies God's power to inflict harm as a test or punishment. This name reminds us that God has the power to inflict harm, but also the power to protect and provide. It encourages humility and submission toGod's will.",
    innerMeaning: "This name connects you to the divine capacity for both challenge and growth. It’s about recognizing that difficulties and obstacles are often necessary for spiritual growth and transformation. It’s about embracing challenges.",
    technique: "Practice embracing challenges and viewing them as opportunities for growth.  When faced with adversity, remember that your capacity for resilience is a gift from the divine.",
    relatedNames: ["An-Nafi", "Al-Qadir"],
    orderNumber: 91,
    category: nameCategories.POWER
  },
  {
    arabicName: "النَّافِعُ",
    transliteration: "An-Nafi",
    pronunciation: "an-NAA-fi",
    meaning: "The Creator of Good",
    description: "The Creator of Good - The One who makes harm reach to whoever He willed and benefits to whoever He willed.",
    detailedExplanation: "An-Nafi', the Creator of Good, emphasizes God's power to bestow blessings and benefits.  This name reminds us that God is the source of all good, and that He bestows His blessings upon those who are deserving. It inspires gratitude and appreciation for God's generosity.",
    innerMeaning: "This name connects you to the divine capacity for creation and abundance. It’s about recognizing your own potential for creating good in the world and sharing your gifts with others. It’s about generosity and compassion.",
    technique: "Practice creating good in the world.  Share your time, talents, and resources with others. When faced with negativity, remember that your capacity for creating good is limitless.",
    relatedNames: ["Ad-Darr", "Al-Qadir"],
    orderNumber: 92,
    category: nameCategories.POWER
  },
  {
    arabicName: "النُّورُ",
    transliteration: "An-Nur",
    pronunciation: "an-NOOR",
    meaning: "The Light",
    description: "The Light - The One who guides whoever He willed by His light, the light of the heavens and the earth.",
    detailedExplanation: "An-Nur, the Light, signifies God as the ultimate source of guidance and illumination. This name reminds us that God is our guide, leading ustowards truth and enlightenment. It inspires a seeking of knowledge and a commitment to following God's path.",
    innerMeaning: "This name connects you to the divine light of wisdom and understanding. It’s about recognizing your own inner light and using it to guide your path. It’s about clarity and insight.",
    technique: "Practice mindfulness and meditation to connect with your inner light. Seek knowledge and understanding.  When faced with darkness, remember that your capacity for light is limitless.",
    relatedNames: ["Al-Hadi", "Al-Haqq"],
    orderNumber: 93,
    category: nameCategories.GUIDANCE
  },
  {
    arabicName: "الْهَادِي",
    transliteration: "Al-Hadi",
    pronunciation: "al-HAA-di",
    meaning: "The Guide",
    description: "The Guide - The One whom with His guidance His believing servants were guided, and with His guidance the living beings have been guided to what is beneficial for them.",
    detailedExplanation: "Al-Hadi, the Guide, emphasizes God's role in leading and directing His creation. This name reminds us that God provides guidance and direction in our lives, leading us towards righteousness and fulfillment. It inspires trust and reliance on God's guidance.",
    innerMeaning: "This name connects you to the divine capacity for guidance and direction.  It’s about recognizing your own inner wisdom and trusting your ability to find your way. It’s about intuition and trust.",
    technique: "Practice trusting your intuition and inner guidance.  Seek out mentors and teachers who can offer support and direction. When faced with uncertainty, remember that your capacity for guidance is limitless.",
    relatedNames: ["An-Nur", "Ar-Rashid"],
    orderNumber: 94,
    category: nameCategories.GUIDANCE
  },
  {
    arabicName: "الْبَدِيعُ",
    transliteration: "Al-Badi",
    pronunciation: "al-ba-DEEE",
    meaning: "The Originator",
    description: "The Originator - The One who created the creation and formed it without any preceding example.",
    detailedExplanation: "Al-Badi', the Originator, highlights God's unique and unparalleled creativity. This name reminds us that God's creation is without precedent, a testament to His infinite imagination and power. It inspires awe and wonder at the Divine's creative genius.",
    innerMeaning: "This name connects you to the divine spark of creativity and innovation. It’s about recognizing your own unique talents and gifts, and using them to create something new and meaningful. It’s about originality and innovation.",
    technique: "Practice cultivating your creativity and imagination.  Engage in creative activities that allow you to express your inner vision. When faced with creative blocks, remember that your capacity for originality is limitless.",
    relatedNames: ["Al-Khaliq", "Al-Musawwir"],
    orderNumber: 95,
    category: nameCategories.CREATION
  },
  {
    arabicName: "الْبَاقِي",
    transliteration: "Al-Baqi",
    pronunciation: "al-BAA-qi",
    meaning: "The Everlasting",
    description: "The Everlasting - The One that the state of non-existence is impossible for Him.",
    detailedExplanation: "Al-Baqi, the Everlasting, signifies God's eternal and unchanging nature. This name reminds us that God's existence is without end, transcending time and space. It inspires trust and reliance on God's eternal presence and power.",
    innerMeaning: "This name connects you to the eternal and unchanging aspects of the divine. It’s about recognizing your own inner strength and resilience, and trusting in your ability to persevere through life’s challenges.  It’s about enduring strength.",
    technique: "Practice mindfulness and meditation to connect with your inner self.  Live in alignment with your values and purpose. When faced with challenges, remember that your capacity for eternity is limitless.",
    relatedNames: ["Al-Hayy", "Al-Qayyum"],
    orderNumber: 96,
    category: nameCategories.LIFE
  },
  {
    arabicName: "الْوَارِثُ",
    transliteration: "Al-Warith",
    pronunciation: "al-WAA-rith",
    meaning: "The Inheritor",
    description: "The Inheritor - The One who remains after the creatures have perished.",
    detailedExplanation: "Al-Warith, the Inheritor, emphasizes God's ultimate dominion and control over all creation. This name reminds us that God will ultimately inherit all things, and that His power and authority will endure forever. It inspires humility and submission to God's will.",
    innerMeaning: "This name connects you to the divine principle of legacy and enduring impact. It’s about recognizing the importance of leaving a positive mark on the world and creating something that will last. It’s about purpose and legacy.",
    technique: "Practice living a life of purpose and meaning.  Strive to create something that will have a lasting impact on the world. When faced with challenges, remember that your capacity for legacy is limitless.",
    relatedNames: ["Al-Baqi", "Al-Hayy"],
    orderNumber: 97,
    category: nameCategories.LIFE
  },
  {
    arabicName: "الرَّشِيدُ",
    transliteration: "Ar-Rashid",
    pronunciation: "ar-ra-SHEED",
    meaning: "The Guide to the Right Path",
    description: "The Guide to the Right Path - The One who guides His creatures to what is beneficial for them.",
    detailedExplanation: "Ar-Rashid, the Guide to the Right Path, emphasizes God's role in leading and guiding His creation towards righteousness and truth. This name reminds us that God provides guidance and direction in our lives, leading us towards a fulfilling and meaningful existence. It inspires trust and reliance on God's guidance.",
    innerMeaning: "This name connects you to the divine capacity for guidance and direction. It’s about recognizing your own inner wisdom and trusting your ability to find your way. It’s about intuition and discernment.",
    technique: "Practice trusting your intuition and inner guidance. Seek out mentors and teachers who can offer support and direction. When faced with uncertainty, remember that your capacity for guidance is limitless.",
    relatedNames: ["Al-Hadi", "Al-Waliyy"],
    orderNumber: 98,
    category: nameCategories.GUIDANCE
  },
  {
    arabicName: "الصَّبُورُ",
    transliteration: "As-Sabur",
    pronunciation: "as-sa-BOOR",
    meaning: "The Patient",
    description: "The Patient - The One who does not quickly punish the sinners.",
    detailedExplanation: "As-Sabur, the Patient, highlights God's forbearance and long-suffering. This name reminds us that God does not rush to judgment, but rather gives time for repentance and amends. It encourages patience and understanding in our dealings with others, mirroring God's own patience.",
    innerMeaning: "This name connects you to the divine capacity for patience and perseverance. It’s about recognizing the importance of allowing time for growth and transformation, both in yourself and others. It’s about resilience and understanding.",
    technique: "Practice patience and understanding in your interactions. Allow time for growth and transformation. When faced with anger or frustration, remember that patience is a virtue.",
    relatedNames: ["Al-Halim", "Al-Ghafur"],
    orderNumber: 99,
    category: nameCategories.FORGIVENESS
  }
];